name: Dockcross Action Sandbox
on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: docker pull
        run: |
          mkdir build
          docker build -f docker/Dockerfile -t myimage .
          docker images

      - name: get helper script
        run: |
          docker run --rm myimage > ./dockcross
          ls -alh
          chmod +x ./dockcross

      - name: run cmake
        run: |
          ./dockcross bash -c "cmake -S . -B build"
          ls -alh build

      - name: run make
        run: |
          ./dockcross bash -c "make --directory=build"
          ls -alh build
          ls -alh build/src
          file build/src/main.exe

      - name: upload hello artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello
          path: build/src/main.exe

  Execute:
    needs: Build
    runs-on: windows-2016

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: get executable artifact
        uses: actions/download-artifact@v2
        with:
          name: hello
          path: build\src

      - name: Hello ?
        run: |
          dir
          cd build\src
          start main.exe